package edu.utap.guessthemovie.model

import com.google.firebase.Timestamp
import com.google.firebase.firestore.DocumentId
import com.google.firebase.firestore.ServerTimestamp

data class ScoreMeta (
    var name: String = "",
    var ownerUid: String = "",
    var score: Int = 0,
    // Written on the server
    @ServerTimestamp
    val timeStamp: Timestamp? = null,
    // firestoreID is generated by firestore, used as primary key
    @DocumentId
    var firestoreID: String = ""
)