package edu.utap.guessthemovie

data class Movie(val title: String, val year: Int)

class Movies {
    companion object {
        private var MovieDataList = listOf (
            Movie("Snow White and the Seven Dwarfs", 1937),
            Movie("Gone With the Wind", 1939),
            Movie("Fantasia", 1940),
            Movie("Pinocchio", 1940),
            Movie("Bambi", 1942),
            Movie("The Best Years of Our Lives", 1946),
            Movie("Cinderella", 1950),
            Movie("The Greatest Show on Earth", 1952),
            Movie("The Robe", 1953),
            Movie("Lady and the Tramp", 1955),
            Movie("The Ten Commandments", 1956),
            Movie("Around the World in 80 Days", 1956),
            Movie("The Bridge On The River Kwai", 1957),
            Movie("Ben-Hur", 1959),
            Movie("Sleeping Beauty", 1959),
            Movie("Swiss Family Robinson", 1960),
            Movie("101 Dalmatians", 1961),
            Movie("West Side Story", 1961),
            Movie("Lawrence of Arabia", 1962),
            Movie("Cleopatra", 1963),
            Movie("It's a Mad, Mad, Mad, Mad World", 1963),
            Movie("Mary Poppins", 1964),
            Movie("Goldfinger", 1964),
            Movie("My Fair Lady", 1964),
            Movie("The Sound of Music", 1965),
            Movie("Doctor Zhivago", 1965),
            Movie("Thunderball", 1965),
            Movie("The Graduate", 1967),
            Movie("The Jungle Book", 1967),
            Movie("Butch Cassidy and the Sundance Kid", 1969),
            Movie("Love Story", 1970),
            Movie("Airport", 1970),
            Movie("M*A*S*H", 1970),
            Movie("The Godfather", 1972),
            Movie("The Poseidon Adventure", 1972),
            Movie("The Exorcist", 1973),
            Movie("The Sting", 1973),
            Movie("American Graffiti", 1973),
            Movie("Blazing Saddles", 1974),
            Movie("The Towering Inferno", 1974),
            Movie("Jaws", 1975),
            Movie("The Rocky Horror Picture Show", 1975),
            Movie("One Flew Over the Cuckoo's Nest", 1975),
            Movie("Rocky", 1976),
            Movie("Star Wars: Episode IV - A New Hope", 1977),
            Movie("Smokey and the Bandit", 1977),
            Movie("Grease", 1978),
            Movie("National Lampoon's Animal House", 1978),
            Movie("Superman", 1978),
            Movie("Star Wars: Episode V - The Empire Strikes Back", 1980),
            Movie("Raiders of the Lost Ark", 1981),
            Movie("E.T.  The Extra-Terrestrial", 1982),
            Movie("Tootsie", 1982),
            Movie("Star Wars: Episode VI - Return of the Jedi", 1983),
            Movie("Ghostbusters", 1984),
            Movie("Beverly Hills Cop", 1984),
            Movie("Indiana Jones and the Temple of Doom", 1984),
            Movie("Back to the Future", 1985),
            Movie("Batman", 1989),
            Movie("Home Alone", 1990),
            Movie("Jurassic Park", 1993),
            Movie("The Lion King", 1994),
            Movie("Forrest Gump", 1994),
            Movie("Independence Day", 1996),
            Movie("Twister", 1996),
            Movie("Titanic", 1997),
            Movie("Men in Black", 1997),
            Movie("Star Wars: Episode I - The Phantom Menace", 1999),
            Movie("The Sixth Sense", 1999),
            Movie("Harry Potter and the Sorcerer's Stone", 2001),
            Movie("The Lord of the Rings: The Fellowship of the Ring", 2001),
            Movie("The Lord of the Rings: The Two Towers", 2002),
            Movie("Harry Potter and the Chamber of Secrets", 2002),
            Movie("Spider-Man", 2002),
            Movie("Star Wars: Episode II - Attack of the Clones", 2002),
            Movie("The Lord of the Rings: The Return of the King", 2003),
            Movie("Finding Nemo", 2003),
            Movie("Pirates of the Caribbean: The Curse of the Black Pearl", 2003),
            Movie("Shrek 2", 2004),
            Movie("Harry Potter and the Prisoner of Azkaban", 2004),
            Movie("Spider-Man 2", 2004),
            Movie("The Passion of the Christ", 2004),
            Movie("Harry Potter and the Goblet of Fire", 2005),
            Movie("Star Wars: Episode III - Revenge of the Sith", 2005),
            Movie("Pirates of the Caribbean: Dead Man's Chest", 2006),
            Movie("Pirates of the Caribbean: At World's End", 2007),
            Movie("Harry Potter and the Order of the Phoenix", 2007),
            Movie("Spider-Man 3", 2007),
            Movie("Shrek the Third", 2007),
            Movie("Transformers", 2007),
            Movie("The Dark Knight", 2008),
            Movie("Iron Man", 2008),
            Movie("Indiana Jones and the Kingdom of the Crystal Skull", 2008),
            Movie("Avatar", 2009),
            Movie("Harry Potter and the Half-Blood Prince", 2009),
            Movie("Ice Age: Dawn of the Dinosaurs", 2009),
            Movie("Transformers: Revenge of the Fallen", 2009),
            Movie("The Twilight Saga: New Moon", 2009),
            Movie("Up", 2009),
            Movie("Toy Story 3", 2010),
            Movie("Alice in Wonderland", 2010),
            Movie("Harry Potter and the Deathly Hallows, Part 1", 2010),
            Movie("Inception", 2010),
            Movie("Iron Man 2", 2010),
            Movie("The Twilight Saga: Eclipse", 2010),
            Movie("Harry Potter and the Deathly Hallows, Part 2", 2011),
            Movie("Transformers: Dark of the Moon", 2011),
            Movie("Pirates of the Caribbean: On Stranger Tides", 2011),
            Movie("Marvel's The Avengers", 2012),
            Movie("Skyfall", 2012),
            Movie("The Dark Knight Rises", 2012),
            Movie("The Hobbit: An Unexpected Journey", 2012),
            Movie("Ice Age: Continental Drift", 2012),
            Movie("The Twilight Saga: Breaking Dawn, Part 2", 2012),
            Movie("The Hunger Games", 2012),
            Movie("Frozen", 2013),
            Movie("Iron Man 3", 2013),
            Movie("Despicable Me 2", 2013),
            Movie("The Hobbit: The Desolation of Smaug", 2013),
            Movie("The Hunger Games: Catching Fire", 2013),
            Movie("Transformers: Age of Extinction", 2014),
            Movie("The Hobbit: The Battle of the Five Armies", 2014),
            Movie("American Sniper", 2014),
            Movie("The Hunger Games: Mockingjay - Part 1", 2014),
            Movie("Guardians of the Galaxy", 2014),
            Movie("Star Wars: Episode VII - The Force Awakens", 2015),
            Movie("Jurassic World", 2015),
            Movie("Furious 7", 2015),
            Movie("Avengers: Age of Ultron", 2015),
            Movie("Minions", 2015),
            Movie("Spectre", 2015),
            Movie("Inside Out", 2015),
            Movie("Captain America: Civil War", 2016),
            Movie("Rogue One: A Star Wars Story", 2016),
            Movie("Finding Dory", 2016),
            Movie("Zootopia", 2016),
            Movie("The Jungle Book", 2016),
            Movie("The Secret Life of Pets", 2016),
            Movie("Batman v Superman: Dawn of Justice", 2016),
            Movie("Fantastic Beasts and Where to Find Them", 2016),
            Movie("Deadpool", 2016),
            Movie("Suicide Squad", 2016),
            Movie("Star Wars: Episode VIII - The Last Jedi", 2017),
            Movie("Beauty and the Beast", 2017),
            Movie("The Fate of the Furious", 2017),
            Movie("Despicable Me 3", 2017),
            Movie("Jumanji: Welcome to the Jungle", 2017),
            Movie("Spider-Man: Homecoming", 2017),
            Movie("Wolf Warrior 2", 2017),
            Movie("Guardians of the Galaxy Vol. 2", 2017),
            Movie("Thor: Ragnarok", 2017),
            Movie("Wonder Woman", 2017),
            Movie("Coco", 2017),
            Movie("Pirates of the Caribbean: Dead Men Tell No Tales", 2017),
            Movie("It", 2017),
            Movie("Avengers: Infinity War", 2018),
            Movie("Black Panther", 2018),
            Movie("Jurassic World: Fallen Kingdom", 2018),
            Movie("Incredibles 2", 2018),
            Movie("Aquaman", 2018),
            Movie("Bohemian Rhapsody", 2018),
            Movie("Venom", 2018),
            Movie("Mission: Impossible - Fallout", 2018),
            Movie("Deadpool 2", 2018),
            Movie("Avengers: Endgame", 2019),
            Movie("The Lion King", 2019),
            Movie("Frozen II", 2019),
            Movie("Spider-Man: Far from Home", 2019),
            Movie("Captain Marvel", 2019),
            Movie("Joker", 2019),
            Movie("Star Wars: Episode IX - The Rise of Skywalker", 2019),
            Movie("Toy Story 4", 2019),
            Movie("Aladdin", 2019),
            Movie("Jumanji: The Next Level", 2019),
            Movie("Spider-Man: No Way Home", 2021),
            Movie("No Time to Die", 2021),
            Movie("Hi, Mom", 2021),
            Movie("Top Gun: Maverick", 2022),
            Movie("Jurassic World Dominion", 2022),
            Movie("Doctor Strange in the Multiverse of Madness", 2022),
            Movie("Minions: The Rise of Gru", 2022),
            Movie("The Batman", 2022),
            Movie("Thor: Love and Thunder", 2022),
        )
    }
    fun fetchOneMovie(): Movie {
        val size = MovieDataList.size
        val MoviePick = (0 until size).random()
        return MovieDataList[MoviePick]
    }
}